### PR TITLE
Ensure options object is initialized in self.get when using promises.

### LINKED ISSUE #59: Bug with .wrap and promises in 0.3.0
Version 0.3.0 introduced a bug when using the `.wrap` method with promises. I have created some new `.wrap` tests to reproduce the issue and will be submitting a PR to resolve it.

```js
TypeError: Cannot set property 'parse' of undefined
    at Object.self.get (index.js:183:19)
    at Object.self.wrap (node_modules/cache-manager/lib/caching.js:99:20)
    at node_modules/cache-manager/lib/caching.js:48:18
    at wrapPromise (node_modules/cache-manager/lib/caching.js:47:16)
    at Object.self.wrap (node_modules/cache-manager/lib/caching.js:92:20)
    at Context.<anonymous> (test/lib/redis-store-spec.js:507:8)
```

### PR DESCRIPTION
**Pull request by jeff-kilbride**
When using the `.wrap` method with promises, it is possible for the `options` object to not be properly initialized in `self.get`. I have added an explicit initialization on line 183 to fix this error. I have also added promise-based tests for the `.wrap` method to both spec files.

This resolves #59.

Sorry for all the issues! This should probably go as `0.3.1` as soon as you guys have reviewed it. Hopefully, this will be the last of the problems with the `.wrap` function.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -180,6 +180,7 @@ function redisStore(args) {
       cb = options;
       options = {};
     }
+    options = options || {};
```
Comment (mrister) [inline index.js]: 👍
